//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   void accept(visitor.Visitor v);
   <R,A> R accept(visitor.GJVisitor<R, A> v, A argu);
   <R> R accept(visitor.GJNoArguVisitor<R> v);
   <A> void accept(visitor.GJVoidVisitor<A> v, A argu);
}

