//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends Node {
   void addNode(Node n);
   Node elementAt(int i);
   java.util.Enumeration<Node> elements();
   int size();

   void accept(visitor.Visitor v);
   <R,A> R accept(visitor.GJVisitor<R, A> v, A argu);
   <R> R accept(visitor.GJNoArguVisitor<R> v);
   <A> void accept(visitor.GJVoidVisitor<A> v, A argu);
}

